name: Ian Manger Voice Over
favicon: null
layout_spectrum: 0.01874
typography_spectrum: 0.65442
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#afc8dd'
    - '#5d9bb9'
    - '#002e3c'
    - '#00697f'
    - '#527184'
  brandStrength: 0.625
  lightness: 0.875
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
